# Site settings
title: Archaeron
email: your_email@example.com
author: Nicolas
description: "Some posts about programming"
baseurl: ""
url: "http://archaeron.github.io"
google_analytics: 

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
